spring:
  application:
    name: nacos-consumers
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.123.17:8848

server:
  port: 8851


management:
  endpoints:
    web:
      exposure:
        include: "*"